### ISSUE TITLE
Implement #[derive(Debug)] for generated structs

### ISSUE THREAD

**Issue by radekg** [maximg/thrift#25]
Implement `#[derive(Debug)]` for generated structs. This will allow using generated structures with `println!` and similar macros.

**Comment by maximg** [comment]
Good idea, you want to submit a PR for this? I had a look at your change and not sure about the changes to the commented out code, if you want to put them in maybe do it as a separate PR and clarify them a bit. Thanks!

**Comment by radekg** [comment]
My bad for the commented out code. Will change to what it was and rebase. A leftover after checking how to get the code generated ;)

**Comment by radekg** [comment]
Here we go. Apologies for the previous one.
