### ISSUE TITLE
Implement single-threaded server

### ISSUE THREAD

**Issue by maximg** [maximg/thrift#26]
Similar to C++ TSimpleServer: very basic single-threaded server. This includes the subset of server-side code generation so that the tutorial example can be compiled and run. Full server-side codegen is done as a separate issue.

**Comment by gsingh93** [comment]
I've started work on this here: https://github.com/gsingh93/thrift/tree/simple-server

**Comment by maximg** [comment]
Thanks @gsingh93 for submitting, looks good! Closing the issue.
