### ISSUE TITLE
Clean up ThriftErr

### ISSUE THREAD

**Issue by maximg** [maximg/thrift#35]
See discussion in #14: some errors are not used and most of them can be moved to a ProtocolError, so that we have a nice enum:

```
  TransportErr(...),
  ProtocolErr(...),
  UserErr(...)
```

**Comment by maximg** [comment]
@gsingh93 I believe this is what we have discussed in #14. Feel free to tweak the names of the types when adding support for exceptions.

**Comment by gsingh93** [comment]
Looks good in general, I made some comments on the commit itself.

**Comment by maximg** [comment]
Thanks, I will look into cleaning up the imports, they can be made more consistent.

**Comment by maximg** [comment]
Finalized the cleanup in 5385008, closing.
